"""Train the Iris classifier and persist the model artifact + model card.

Trains a scikit-learn pipeline (standardisation + logistic regression) on a
train/test split, evaluates it on the held-out set, and writes:

    * model.joblib   - the serialized pipeline used by the serving app.
    * model_card.md  - a short card documenting metrics ACTUALLY computed here.

Run:
    python train.py
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

import joblib
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parent
MODEL_PATH = ROOT / "model.joblib"
MODEL_CARD_PATH = ROOT / "model_card.md"

RANDOM_STATE = 42
TEST_SIZE = 0.2


def build_pipeline() -> Pipeline:
    """Construct the standardisation + logistic-regression pipeline."""
    return Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            (
                "clf",
                LogisticRegression(max_iter=1000, random_state=RANDOM_STATE),
            ),
        ]
    )


def train() -> dict[str, object]:
    """Train and evaluate the model, returning a metrics dictionary."""
    data = load_iris()
    x_train, x_test, y_train, y_test = train_test_split(
        data.data,
        data.target,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=data.target,
    )

    pipeline = build_pipeline()
    pipeline.fit(x_train, y_train)

    predictions = pipeline.predict(x_test)
    accuracy = accuracy_score(y_test, predictions)
    macro_f1 = f1_score(y_test, predictions, average="macro")
    report = classification_report(
        y_test, predictions, target_names=list(data.target_names)
    )

    joblib.dump(pipeline, MODEL_PATH)

    return {
        "accuracy": accuracy,
        "macro_f1": macro_f1,
        "report": report,
        "n_train": int(len(x_train)),
        "n_test": int(len(x_test)),
        "target_names": list(data.target_names),
    }


def write_model_card(metrics: dict[str, object]) -> None:
    """Write model_card.md using only metrics computed in :func:`train`."""
    today = dt.date.today().isoformat()
    card = f"""# Model Card — Iris Classifier

*Generated by `train.py` on {today}. All figures below are computed on a
held-out test split during training — nothing here is hand-edited.*

## Overview

- **Task:** multiclass classification of Iris flowers into
  {", ".join(str(n) for n in metrics["target_names"])}.
- **Algorithm:** `StandardScaler` + `LogisticRegression` (scikit-learn `Pipeline`).
- **Dataset:** the classic Iris dataset bundled with scikit-learn (150 samples,
  4 numeric features).

## Training setup

- Train/test split: {int((1 - TEST_SIZE) * 100)}% / {int(TEST_SIZE * 100)}%,
  stratified by class, `random_state={RANDOM_STATE}`.
- Training samples: {metrics["n_train"]}
- Test samples: {metrics["n_test"]}

## Metrics (held-out test set)

- **Accuracy:** {metrics["accuracy"]:.4f}
- **Macro F1:** {metrics["macro_f1"]:.4f}

### Per-class report

```
{metrics["report"]}
```

## Intended use & limitations

This is a **portfolio/demo** model. Iris is a small, clean, well-separated
dataset; strong scores here say nothing about performance on real-world data.
It exists to demonstrate an end-to-end MLOps serving path, not to be a
state-of-the-art classifier.
"""
    MODEL_CARD_PATH.write_text(card, encoding="utf-8")


def main() -> None:
    """Entry point: train, persist artifact, and write the model card."""
    metrics = train()
    write_model_card(metrics)
    print(f"Saved model to {MODEL_PATH}")
    print(f"Saved model card to {MODEL_CARD_PATH}")
    print(
        f"Accuracy={metrics['accuracy']:.4f}  Macro-F1={metrics['macro_f1']:.4f}"
    )


if __name__ == "__main__":
    main()
